<html>
<body>
<h2>This is a normal heading</h2>
<?php
echo "<p>This is text generated by PHP code<br>\n";
?>
<h2>This is another normal heading</h2>
<?php
echo "<p>This is another section generated by PHP code<br>\n";
?>
</body>
</html>